version: "3.3"

services:
  squid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squid
    image: squid
    #network_mode: host
    ports:
      - "3128:3128"
    volumes:
      - ./cache:/var/spool/squid
      - ./squid:/etc/squid
    restart: always
